\documentclass{article}

\begin{document}
\SweaveOpts{concordance=TRUE}

<<echo=F>>=

MRR <- 30 # Monthly subscription of $30 
AvgDuration <- mean(1:2) # Average Contract Duration between 1 and 2 months 
Duration <- 1 # Typical contract duration
ARPA <- MRR * AvgDuration # Average Monthly Recurring Revenue per Account
Months <- 12 # Months of simulation 
Customers <- 60 # Initial influx of Customers (Month 1)
Margin <- 0.45 # Average sale margin
R <- 0.10 # Discount/Interest rate
Ad_Budget <- 200 # Amount spent acquiring customers monthly

@


\begin{enumerate}
  \item For a monthly subscription of \$$\Sexpr{MRR}$, the client recieves 2 ties per month.
  \item The subscription contracts are monthly, with the average user initially signing up for either 1 or 2 months, which implies a starting average contract duration of $\Sexpr{AvgDuration}$ months and $\Sexpr{Duration}$ thereafter.    
  \item The Average Revenue per Account (ARPA) is therefore initially \$$\Sexpr{ARPA}$.
  \item The initial customer base is assumed to be $\Sexpr{Customers}$.
  \item The discount rate is assumed to be $\Sexpr{(R*100)}$\%.
  \item The initial advertising budget for this firm is assumed to be \$$\Sexpr{Ad_Budget}$\.
\end{enumerate}



\end{document}